name: Create Release with Tag Message
on:
  push:
    tags:
      - 'v*' # Запускать workflow при создании тега, начинающегося с 'v'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get tag message
        id: get_tag_message
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          TAG_MESSAGE=$(git tag -l --format='%(contents)' $TAG_NAME)
          echo "tag_message=$TAG_MESSAGE" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.get_tag_message.outputs.tag_message }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}